Handle PermissionError when looking for the defaults or groups files
wvandeun/nornir_netbox pull request #43
Opened 2022-08-17 00:32 UTC by nahun

When checking if the `defaults` or `groups` files exist, it can throw a permissions error. This can happen when running a script with sudo as a different user that doesn't have permission to the current working directory.

2022-08-17 21:05 UTC, wvandeun commented
Thanks for the suggestion.

I see your point but I do have some thoughts about the approach.
I'm not convinced at this stage that the inventory plugin should handle the PermissionError exception.
Wouldn't it be better to signal that exception to the consumer of the plugin that this error occurred? 

With your approach we are completely ignoring the error and not communicating the condition back to the consumer.
Continuing setting up the inventory would not be what I would expect.

The PermissionError could better be handled in the consuming script so it has control over what should happen (ie print/log an error message and exit).

Maybe I'm overseeing something or I may not have enough context to understand what you are trying to achieve?

2022-08-17 21:33 UTC, nahun commented
If it was required that the `groups` or `defaults` file existed and be readable then yes I think the error should be passed to the consuming script. But my thought was that it treats the PermissionError the same as if the file didn't exist. To the plugin, all that matters is that the file is readable (which means it exists and permissions are correct). I think a warning in the log is probably a good idea.

Basically I need the plugin to continue as normal because the script will very often be run in a current working directory that is not readable by the user (since its run with sudo). For example a user logs into our server, gets placed into their home directory, and then just runs the script from there with something like `sudo -u otheruser thescript`. The "otheruser" is not root and does not have permissions to the user's home directory.

If I'm able to make the plugin ignore the PermissionsError another way (via an option) that would be fine as well.

2022-08-18 13:01 UTC, wvandeun commented
I would be open to an implementation, if the default behaviour of the plugin doesn't change. The option should be disabled by default. A logging message should be created (warning level?) when the option gets enabled.
Also tests would need to be added for this behaviour.

2022-08-18 19:13 UTC, nahun commented
I updated the branch. Something like that?

2022-08-19 22:58 UTC, wvandeun commented on nornir_netbox/plugins/inventory/netbox.py
> +                raise PermissionError(e)
`raise` should be sufficient here to re-raise the current handled exception
would add a logging message (error level)

2022-08-19 23:01 UTC, wvandeun commented on nornir_netbox/plugins/inventory/netbox.py
> +            warnings.warn("Error ignored while reading file: {}".format(e))
Can we use the logging library here instead?
The message can be more explicit, something like `Unable to read {file} due to a permission issue`

2022-08-19 23:01 UTC, wvandeun commented on nornir_netbox/plugins/inventory/netbox.py
> +                raise PermissionError(e)
same remark as above

2022-08-19 23:03 UTC, wvandeun requested changes
Can you have a look at the comments and also document the newly added option?
Still need to review the tests.

2022-08-20 00:45 UTC, nahun commented
Pushed changes that should cover those comments. Thanks!

2022-09-08 22:08 UTC, wvandeun commented
Made a few suggestions/improvements.
Are you ok with these?

2022-09-08 22:22 UTC, nahun commented
Looks good, didn't know about the `tmp_path` fixture with pytest. Thanks!

2022-09-11 22:01 UTC, merged

2022-09-13 05:48 UTC, wvandeun commented
Thank you for your contribution on this one!