added vm support
wvandeun/nornir_netbox pull request #7
Opened 2020-09-06 08:02 UTC by patrickdaj

Added new option to NetBox inventory module to conditionally add virtual machines in Netbox into inventory.  The option is called include_vms and defaults to False.  The code was re-organized a bit to eliminate duplicatation.

While writing the tests to support this new functionality, I did rename a lot of things and add a bit to aid reusability of the test functions.  Unfortunately I do not have access to anything other than 2.8.9 so I limited my new tests to just 2.8.9.

2020-09-11 22:37 UTC, wvandeun requested changes
Thx for the work on this.

Can you rebase (and review) onto develop branch, the last commit in develop has some changes that you want to look into first.

I haven't reviewed the changes made to the tests yet, since I have some doubts about the newly introduced function. This might affect the tests again, so I will review the tests after that is cleared out.

2020-09-11 22:37 UTC, wvandeun commented on nornir_netbox/plugins/inventory/netbox.py
> +    def _get_resource(self, url: str, params: Dict[str, Any]) -> List[Dict[str, Any]]:
rename the function name to _get_resources

2020-09-11 22:37 UTC, wvandeun commented on nornir_netbox/plugins/inventory/netbox.py
> +        resource: List[Dict[str, Any]] = []
rename variables to resources

2020-09-11 22:37 UTC, wvandeun commented on nornir_netbox/plugins/inventory/netbox.py
> +    def _get_hosts(
I'm not really sure why you are introducing this function. In my opinion it's not really needed.

2020-09-11 22:37 UTC, wvandeun commented on nornir_netbox/plugins/inventory/netbox.py
> +        include_vms: bool = False,
add this argument to the docstring + explanation

2020-09-12 05:15 UTC, closed without merging

2020-09-12 05:25 UTC, patrickdaj commented
Guess I'll open another PR as my force push closed it I assume.